import React from "react";
import { Button } from "@/components/ui/button";
import { ArrowRight } from "lucide-react";

const HeroNew = () => {
  return (
    <div className="relative pt-20 pb-12 md:pt-32 md:pb-24 overflow-hidden">
      <div className="absolute inset-0 z-0">
        <div className="absolute inset-0 bg-gradient-to-br from-blue-50 via-purple-50 to-white" />
        <div className="absolute top-0 left-0 right-0 h-48 bg-gradient-radial from-brand-purple/20 to-transparent opacity-50" />
      </div>
      
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        <div className="flex flex-col lg:flex-row items-center">
          <div className="text-center lg:text-left lg:max-w-2xl">
            <h1 className="text-4xl sm:text-5xl md:text-6xl font-extrabold tracking-tight">
              <span className="block">Revolutionize Your</span>
              <span className="block gradient-text mt-1">Project Management</span>
            </h1>
            <p className="mt-6 text-lg md:text-xl text-gray-600 max-w-3xl">
              Streamline your workflow with your assistant, smart task management, 
              daily reports and seamless file attachments. All in one powerful platform.
            </p>
            <div className="mt-8 flex flex-col sm:flex-row justify-center lg:justify-start gap-4">
              <Button className="btn-primary text-lg flex items-center gap-2 px-8 py-6">
                Start for free <ArrowRight className="h-5 w-5 ml-1" />
              </Button>
              {/* <Button variant="outline" className="btn-secondary text-lg px-8 py-6">
                Book a demo
              </Button> */}
            </div>
            <p className="mt-4 text-sm text-gray-500">No credit card required</p>
          </div>
          <div className="mt-12 lg:mt-0 lg:ml-8 w-full max-w-lg mx-auto">
            <div className="relative">
              <div className="absolute -top-4 -left-4 w-72 h-72 bg-brand-purple/10 rounded-full filter blur-2xl opacity-70 animate-float"></div>
              <div className="absolute -bottom-8 -right-8 w-72 h-72 bg-brand-blue/10 rounded-full filter blur-2xl opacity-70 animate-float" style={{ animationDelay: '2s' }}></div>
              
              <div className="bg-white rounded-2xl shadow-xl overflow-hidden border border-gray-100 relative z-10">
                <div className="bg-gradient-to-r from-brand-purple to-brand-blue p-1">
                  <div className="bg-white rounded-t-xl p-2">
                    <div className="flex space-x-2">
                      <div className="w-3 h-3 bg-red-400 rounded-full"></div>
                      <div className="w-3 h-3 bg-yellow-400 rounded-full"></div>
                      <div className="w-3 h-3 bg-green-400 rounded-full"></div>
                    </div>
                  </div>
                </div>
                <div className="p-4">
                  <div className="flex justify-between items-center border-b pb-3">
                    <h3 className="font-medium">Project Dashboard</h3>
                    <span className="text-sm text-gray-500">Today</span>
                  </div>
                  <div className="grid grid-cols-2 gap-3 mt-3">
                    <div className="bg-gray-50 p-3 rounded-lg">
                      <p className="text-sm font-medium text-gray-700">Tasks Created</p>
                      <p className="text-2xl font-bold text-brand-purple">24</p>
                    </div>
                    <div className="bg-gray-50 p-3 rounded-lg">
                      <p className="text-sm font-medium text-gray-700">Completed</p>
                      <p className="text-2xl font-bold text-brand-green">16</p>
                    </div>
                  </div>
                  <div className="mt-4 space-y-3">
                    <div className="bg-gray-50 p-3 rounded-lg flex justify-between items-center">
                      <div className="flex items-center">
                        <div className="w-2 h-8 bg-brand-purple rounded-full mr-3"></div>
                        <div>
                          <p className="font-medium">Design Review</p>
                          <p className="text-xs text-gray-500">Assigned to Your Assistant</p>
                        </div>
                      </div>
                      <span className="text-xs bg-gray-200 px-2 py-1 rounded">2:00 PM</span>
                    </div>
                    <div className="bg-gray-50 p-3 rounded-lg flex justify-between items-center">
                      <div className="flex items-center">
                        <div className="w-2 h-8 bg-brand-blue rounded-full mr-3"></div>
                        <div>
                          <p className="font-medium">EOD Report</p>
                          <p className="text-xs text-gray-500">Generated by your assistant</p>
                        </div>
                      </div>
                      <span className="text-xs bg-gray-200 px-2 py-1 rounded">5:30 PM</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default HeroNew;